version: '3.8'

services:
  backend:
    image: ghcr.io/vosiander/llm-key-requestor/backend:latest
    ports:
      - "8000:8000"
    volumes:
      - ./certs:/certs  # Optional: Mount directory for custom certificates
      - ./config/config.yaml:/app/config.yaml  # Mount custom config file
    environment:
      - PYTHONUNBUFFERED=1
      - CONFIG=/app/config.yaml
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  frontend:
    image: ghcr.io/vosiander/llm-key-requestor/frontend:latest
    ports:
      - "5173:5173"
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  default:
    name: llm-key-requestor-network
